using System.Collections;
using System.Collections.Generic;

namespace Assets.Scripts.Model
{
    public static class NamesList
    {
        public static List<string> Names =  new List<string>();
            // Names generated by https://www.fantasynamegenerators.com/english_names.php
            // Louis Spencer
            // Cameron Hussain
            // Jay Marshall
            // Sam Berry
            // Patrick Lawson
            // Chris Young
            // Issac Brennan
            // Carter Durham
            // Bryan Dunn
            // Omar Lucas
            // Bethany Cooper
            // Willow Lowe
            // Amy Brooks
            // Ava Nicholson
            // Matilda Barnes
            // Aiyana Foreman
            // Emmalyn Farmer
            // Allison Bradford
            // Jacqueline Alston
            // Teresa Whitley
            // Glen Johnston
            // Kit Harper
            // Taylor Byrne
            // Casey Ross
            // Rene Woods
            // Reggie Cline
            // Avery Shepherd
            // Aaren Everett
            // Carol Gray
            // Alex Hatfield
            // Ash Williamson
            // Alex Robinson
            // Gene Armstrong
            // Kerry Adams
            // Sidney Moss
            // Jude Roberts
            // Shay Stone
            // Jaden Harmon
            // Brook Weaver
            // Kai Potter
            // Natasha Rees
            // Amy Robertson
            // Madeleine Duncan
            // Tia Day
            // Mia Jordan
            // Aubrianna Everett
            // Dalilah Newman
            // Mary Warner
            // Aviana Wiggins
            // Anabella Stein
            // George Scott
            // Ryan Elliott
            // Leo King
            // Christopher Cooke
            // Matthew Woods
            // Andre Avery
            // Carson Wallace
            // Urijah Navarro
            // Bentlee Rivas
            // Darnell Nelson
            // Rene Berry
            // Skye Burke
            // Justice Wood
            // Val Griffiths
            // Gene Wilkinson
            // Taylor Walsh
            // Cameron Mosley
            // Morgan English
            // Fran Bennett
            // Ashton Gates
            // Alex Houghton
            // Martha Allen
            // Danielle Young
            // Louise Gardner
            // Abbie Reynolds
            // Jocelynn Richards
            // Saanvi Hayden
            // Cristina Parker
            // Georgia Rich
            // Kaia Myers
            // James Elliott
            // Kian Perry
            // Frankie Hawkins
            // Jordan Bailey
            // Aidan Harper
            // Jaylen Avery
            // Braylen Zamora
            // Fletcher Miranda
            // Sterling Farmer
            // Darien Hoover
            // Noel Robertson
            // Franky Graham
            // Vic Hughes
            // Ali Rogers
            // Bennie Jackson
            // Reed Powell
            // Brynn Sutton
            // Quinn Hardin
            // Sam Diaz
            // Rowan Lucas
            // Charlie Griffiths
            // Harley Rees
            // Phoenix Richardson
            // Maddox Ward
            // Quinn Ross
            // Phoenix Curry
            // Franky Simmons
            // Gene Michael
            // Addison Buckley
            // Leslie Kane
            // Maria Hayes
            // Ruby George
            // Faith Patel
            // Emma Edwards
            // Kayleigh Scott
            // Makayla Mathis
            // Libby Murphy
            // Alyssa Parrish
            // Lindsay Huffman
            // Renata King
            // David Walsh
            // Sebastian Clark
            // Blake Matthews
            // Gabriel Smith
            // Dominic Hart
            // Jedidiah Glenn
            // Brayden Black
            // Brentley Conrad
            // Dylan Dunn
            // Brennen Reeves
            // Gabe Black
            // Logan Morris
            // Ali Andrews
            // Ali Lee
            // Bailey Fraser
            // Tanner Bond
            // Denny Gilliam
            // Gabby Small
            // Carol Stephenson
            // Fran Workman
            // Elsie Gallagher
            // Amelie Elliott
            // Harriet Newman
            // Abbie Lewis
            // Anna Cunningham
            // Clarissa Long
            // Karlee Stein
            // Fiona Carver
            // Nahla Camacho
            // Maryam Marsh
            // Jodie Evans
            // Courtney Lloyd
            // Demi Hall
            // Lola Green
            // Anna Watts
            // Kenia Bryant
            // Aimee Bishop
            // Kate Chang
            // Harper Ferguson
            // Lorelai Chaney
            // Anthony Ross
            // Jayden Read
            // Aaron Duncan
            // Jay Gill
            // Evan Shaw
            // Devan Farley
            // Karsen Meyers
            // Kash Buck
            // Weston Sawyer
            // Augustine Mccall
            // Will Dawson
            // Ashton Cook
            // Mel Gibson
            // Blake Porter
            // Lane Gill
            // Bailey Rivera
            // Bret Stanton
            // Robin Norman
            // Brett William
            // Ali Head
            // Lexi Cook
            // Sara Reynolds
            // Charlotte Porter
            // Jasmine Richardson
            // Lauren Robertson
            // Kylee Douglas
            // Rose Strong
            // Olive Mercado
            // Arabella Boone
            // Blair Diaz
            // Zara Hussain
            // Maddison Thomas
            // Keira Stone
            // Sofia Wright
            // Emilia King
            // Raelynn Gordon
            // Annabell Morrison
            // Alissa Mueller
            // Anika Fernandez
            // Esther Cole
            // Jake Roberts
            // Benjamin Jones
            // Riley Reid
            // John Simpson
            // Lucas Wilson
            // Gunner Ayers
            // Neil Gilbert
            // Nathanael Bentley
            // Mayson Lamb
            // Lennox Soto
            // Willy Cunningham
            // Jaden Stone
            // Bev Sutton
            // Casey Wood
            // Glen Bell
            // Phoenix Guthrie
            // Jesse Mejia
            // Carol Perez
            // Ryan Gonzalez
            // Drew Moon
            // Anna Powell
            // Morgan Palmer
            // Alex Williams
            // Sarah West
            // Lexie Hopkins
            // Karis Hopkins
            // Viviana James
            // Anya Dorsey
            // Annabell Webster
            // Moriah Calderon
            // Arthur Allen
            // Arthur Green
            // Jamie Anderson
            // Max Morris
            // Connor Parker
            // Israel Talley
            // Titus Knapp
            // Ayden Griffith
            // Raymond Watts
            // Rowan Sellers
            // Willy Hill
            // Blake Graham
            // Gale Hunt
            // Bev Hill
            // Alexis Barker
            // Ashton Guerra
            // Franky Terry
            // Lynn Downs
            // Quinn Hanson
            // Charlie Lawrence
            // Zoe Harper
            // Nicole Rose
            // Amelie Barrett
            // Poppy Rees
            // Imogen Morris
            // Taylor Gutierrez
            // Lilith Monroe
            // Carmen Hewitt
            // Emma Berry
            // Elisabeth Gill
            // Chelsea Thomson
            // Faith Booth
            // Ella Cunningham
            // Molly Anderson
            // Jodie Burton
            // Kennedy Wright
            // Cassandra Nguyen
            // Emory Pollard
            // Miley Cline
            // Meredith Bolton
        
        static NamesList()
        {
            string namesList = "L. Spencer,C. Hussain,J. Marshall,S. Berry,P. Lawson,C. Young,"
                     + "I. Brennan,C. Durham,B. Dunn,O. Lucas,B. Cooper,W. Lowe,"
                     + "A. Brooks,A. Nicholson,M. Barnes,A. Foreman,E. Farmer,A. Bradford,"
                     + "J. Alston,T. Whitley,G. Johnston,K. Harper,T. Byrne,C. Ross,"
                     + "R. Woods,R. Cline,A. Shepherd,A. Everett,C. Gray,A. Hatfield,"
                     + "A. Williamson,A. Robinson,G. Armstrong,K. Adams,S. Moss,J. Roberts,"
                     + "S. Stone,J. Harmon,B. Weaver,K. Potter,N. Rees,A. Robertson,"
                     + "M. Duncan,T. Day,M. Jordan,A. Everett,D. Newman,M. Warner,"
                     + "A. Wiggins,A. Stein,G. Scott,R. Elliott,L. King,"
                     + "C. Cooke,M. Woods,A. Avery,C. Wallace,U. Navarro,B. Rivas,"
                     + "D. Nelson,R. Berry,S. Burke,J. Wood,V. Griffiths,G. Wilkinson,"
                     + "T. Walsh,C. Mosley,M. English,F. Bennett,A. Gates,A. Houghton,"
                     + "M. Allen,D. Young,L. Gardner,A. Reynolds,J. Richards,S. Hayden,"
                     + "C. Parker,G. Rich,K. Myers,J. Elliott,K. Perry,F. Hawkins,J. Bailey,"
                     + "A. Harper,J. Avery,B. Zamora,F. Miranda,S. Farmer,D. Hoover,N. Robertson,"
                     + "F. Graham,V. Hughes,A. Rogers,B. Jackson,R. Powell,B. Sutton,Q. Hardin,"
                     + "S. Diaz,R. Lucas,C. Griffiths,H. Rees,P. Richardson,M. Ward,Q. Ross,"
                     + "P. Curry,F. Simmons,G. Michael,A. Buckley,L. Kane,M. Hayes,R. George,"
                     + "F. Patel,E. Edwards,K. Scott,M. Mathis,L. Murphy,A. Parrish,L. Huffman,"
                     + "R. King,D. Walsh,S. Clark,B. Matthews,G. Smith,D. Hart,J. Glenn,"
                     + "B. Black,B. Conrad,D. Dunn,B. Reeves,G. Black,L. Morris,A. Andrews,"
                     + "A. Lee,B. Fraser,T. Bond,D. Gilliam,G. Small,C. Stephenson,F. Workman,"
                     + "E. Gallagher,A. Elliott,H. Newman,A. Lewis,A. Cunningham,C. Long,"
                     + "K. Stein,F. Carver,N. Camacho,M. Marsh,J. Evans,C. Lloyd,D. Hall,"
                     + "L. Green,A. Watts,K. Bryant,A. Bishop,K. Chang,H. Ferguson,L. Chaney,"
                     + "A. Ross,J. Read,A. Duncan,J. Gill,E. Shaw,D. Farley,K. Meyers,K. Buck,"
                     + "W. Sawyer,A. Mccall,W. Dawson,A. Cook,M. Gibson,B. Porter,L. Gill,"
                     + "B. Rivera,B. Stanton,R. Norman,B. William,A. Head,L. Cook,S. Reynolds,"
                     + "C. Porter,J. Richardson,L. Robertson,K. Douglas,R. Strong,O. Mercado,"
                     + "A. Boone,B. Diaz,Z. Hussain,M. Thomas,K. Stone,S. Wright,E. King,"
                     + "R. Gordon,A. Morrison,A. Mueller,A. Fernandez,E. Cole,J. Roberts,B. Jones,"
                     + "R. Reid,J. Simpson,L. Wilson,G. Ayers,N. Gilbert,N. Bentley,M. Lamb,"
                     + "L. Soto,W. Cunningham,J. Stone,B. Sutton,C. Wood,G. Bell,P. Guthrie,"
                     + "J. Mejia,C. Perez,R. Gonzalez,D. Moon,A. Powell,M. Palmer,A. Williams,"
                     + "S. West,L. Hopkins,K. Hopkins,V. James,A. Dorsey,A. Webster,M. Calderon,"
                     + "A. Allen,A. Green,J. Anderson,M. Morris,C. Parker,I. Talley,T. Knapp,"
                     + "A. Griffith,R. Watts,R. Sellers,W. Hill,B. Graham,G. Hunt,B. Hill,A. Barker,"
                     + "A. Guerra,F. Terry,L. Downs,Q. Hanson,C. Lawrence,Z. Harper,N. Rose,"
                     + "A. Barrett,P. Rees,I. Morris,T. Gutierrez,L. Monroe,C. Hewitt,E. Berry,"
                     + "E. Gill,C. Thomson,F. Booth,E. Cunningham,M. Anderson,J. Burton,K. Wright,"
                     + "C. Nguyen,E. Pollard,M. Cline,M. Bolton";
            Names.AddRange(namesList.Split(','));
        }

    }
}